[package]
name = "ninetyfive"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lib]
path = "src/ninetyfive.rs"

[dependencies]
anyhow.workspace = true
async-tungstenite.workspace = true
client.workspace = true
edit_prediction.workspace = true
gpui.workspace = true
language.workspace = true
log.workspace = true
project.workspace = true
settings.workspace = true

[dev-dependencies]
